// <auto-generated />
namespace PhantomNet.MessageSender
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.MessageSender.Strings", typeof(Strings).GetTypeInfo().Assembly);

        /// <summary>
        /// There was an error reading template '{0}' at location '{1}'.
        /// </summary>
        internal static string TemplateReadingError
        {
            get { return GetString("TemplateReadingError"); }
        }

        /// <summary>
        /// There was an error reading template '{0}' at location '{1}'.
        /// </summary>
        internal static string FormatTemplateReadingError(object p0, object p1)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("TemplateReadingError"), p0, p1);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
