// <auto-generated />
namespace Resources
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class CommonValidationMessages
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Resources.CommonValidationMessages", typeof(CommonValidationMessages).GetTypeInfo().Assembly);

        /// <summary>
        /// {0} is not a valid email address.
        /// </summary>
        internal static string EmailAddress
        {
            get { return GetString("EmailAddress"); }
        }

        /// <summary>
        /// {0} is not a valid email address.
        /// </summary>
        internal static string FormatEmailAddress(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("EmailAddress"), p0);
        }

        /// <summary>
        /// {0} must have a maximum length of {1}.
        /// </summary>
        internal static string MaxLength
        {
            get { return GetString("MaxLength"); }
        }

        /// <summary>
        /// {0} must have a maximum length of {1}.
        /// </summary>
        internal static string FormatMaxLength(object p0, object p1)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("MaxLength"), p0, p1);
        }

        /// <summary>
        /// {0} must have a minimum length of {1}.
        /// </summary>
        internal static string MinLength
        {
            get { return GetString("MinLength"); }
        }

        /// <summary>
        /// {0} must have a minimum length of {1}.
        /// </summary>
        internal static string FormatMinLength(object p0, object p1)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("MinLength"), p0, p1);
        }

        /// <summary>
        /// Please enter {0}.
        /// </summary>
        internal static string Required
        {
            get { return GetString("Required"); }
        }

        /// <summary>
        /// Please enter {0}.
        /// </summary>
        internal static string FormatRequired(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Required"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
