// <auto-generated />
namespace PhantomNet.Core
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.Core.Strings", typeof(Strings).GetTypeInfo().Assembly);

        /// <summary>
        /// An unknown failure has occured.
        /// </summary>
        internal static string DefaultError
        {
            get { return GetString("DefaultError"); }
        }

        /// <summary>
        /// An unknown failure has occured.
        /// </summary>
        internal static string FormatDefaultError()
        {
            return GetString("DefaultError");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
